version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz

#measures - look at abx prescribing over time
generate_measure:
    run: ehrql:v1 generate-measures analysis/measure_definition.py --output measures.csv 
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures.csv



#generate_report:
 #   run: r:v1 analysis/abx_time_series.r
  #  needs: [generate_measure]
   # outputs:
    #  moderately_sensitive:
     #   chart: output/fq_time_plot.png