version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz

  generate_ctc:
    run: ehrql:v1 generate-dataset analysis/ctc_definition.py --output output/ctc_data.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/ctc_data.csv.gz

#measures - look at abx prescribing over time
  generate_measure:
    run: ehrql:v1 generate-measures analysis/measure_definition.py --output output/measures.csv 
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures.csv

  
  generate_report:
     run: r:v2 analysis/abx_time_series.R
     needs: [generate_measure]
     outputs:
      moderately_sensitive:
        chart1: output/time_plot/abx_quarter_time_plot.png
        chart2: output/time_plot/outcome_quarter_time_plot.png

  generate_cohort:
      run: r:v2 analysis/dataset_manipulate_cohort.R
      needs: [generate_dataset]
      outputs:
        highly_sensitive:
          chart: output/dataset_formatted_cohort.csv

